### PR TITLE
added a conclusion?

### PR DESCRIPTION
**Pull request by Aron-arch**
I added a conclusion to the story, hopefully it will bring some closure.

### CODE REVIEW

**Comment by Aron-arch** [comment]
I did this exercise a little late, sorry.

**Comment by Aron-arch** [comment]
I think I resolved my previous issue.

**Comment by pmongeon** [comment]
Thanks for giving us the opportunity to play around with reopening closed pull requests and stuff.

**Comment by Aron-arch** [comment]
No problem, thanks for giving me the opportunity to present my issue during the lecture.

**Pull request merged**
